apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: 2018-02-06T07:23:05Z
  name: rook-api
  namespace: rook
  ownerReferences:
  - apiVersion: v1alpha1
    blockOwnerDeletion: true
    kind: Cluster
    name: rook
    uid: 721ddaff-0b0e-11e8-8ab2-42010a8a007b
  resourceVersion: "52361"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/rook/roles/rook-api
  uid: 930a6378-0b0e-11e8-8ab2-42010a8a007b
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - pods
  - services
  - nodes
  - configmaps
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  - deployments
  - daemonsets
  - replicasets
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: 2018-02-06T07:23:05Z
  name: rook-api
  namespace: rook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-api
subjects:
- kind: ServiceAccount
  name: rook-api
  namespace: rook
